---
- hosts: all
  become: true
  become_method: sudo

  vars:
    docker_users:
    - ubuntu

  roles:
  - andrelohmann.docker

  tasks:
  - name: update the machine
    apt:
      update_cache: yes

  - name: upgrade the machine
    apt:
      upgrade: full

  - name: include hosts-tasks
    include: hosts-tasks.yml

  - name: activate ipv6 forwarding
    lineinfile:
      dest: /etc/sysctl.conf
      regexp: "^net.ipv6.conf.all.forwarding"
      line: "net.ipv6.conf.all.forwarding=1"
      state: present

  - name: activate forwarding
    command: sysctl -p

  - name: determine swarm status
    shell: "docker info | egrep '^Swarm: ' | cut -d ' ' -f2"
    register: swarm_status

  - name: swarm init
    command: "docker swarm init --advertise-addr 192.168.233.151"
    when: swarm_status.stdout == 'inactive'

  - name: read worker token
    shell: docker swarm join-token -q worker
    register: worker_token

  - name: write worker token to tmp file
    copy:
      content: "{{ worker_token.stdout }}"
      dest: /vagrant/ansible/workertoken
...
