---
- hosts: all
  become: true
  become_method: sudo

  vars:
    docker_users:
    - ubuntu

  roles:
  - andrelohmann.docker

  tasks:
  - name: update the machine
    apt:
      update_cache: yes

  - name: upgrade the machine
    apt:
      upgrade: full

  - name: include hosts-tasks
    include: hosts-tasks.yml
...
